"""
ied_ampwidth_gui_v7.py -- the literature's features, the right filters, a CSD,
and a cross-validated answer to whether any of it tells a dentate spike from
an IED.

WHAT THIS ADDS OVER v6
======================
v6 asked whether amplitude and half-width separate the classes. They barely
do (out-of-fold AUC 0.70). v7 replaces guessing with the feature sets the two
literatures actually use, filtered the way their methods sections filter, and
then -- the part that matters -- scores them OUT OF FOLD instead of in-sample.

  SPECTRAL   fast ripple 250-600 Hz, ripple 80-250 Hz, MUA 600-2000 Hz, each
             in dB against the event's own baseline; their ratio; spectral
             entropy; sustained HFO cycles; FOOOF aperiodic exponent and
             fast-ripple peak power
  MORPHOLOGY amplitude, half-width, maximum slope, sharpness, rise/fall
             asymmetry, post-spike slow wave
  LAMINAR    CSD sink depth and dipole separation, and spatial spread

`ied_ds_lit.py` carries the citations and the band definitions.

THE HEADLINE, AND WHY CROSS-VALIDATION CHANGED IT
=================================================
With 13 IEDs, 296 dentate spikes and seventeen features, an LDA fitted and
scored on the same rows reports AUC 0.93. Out of fold it is 0.82 -- and the
SPECTRAL BLOCK ALONE beats the full set, 0.88 against 0.82. Adding the
morphology and laminar features makes the classifier worse on data it has not
seen, which is what overfitting looks like when there are only thirteen
positives to memorise. The in-sample number is shown beside the cross-
validated one in every panel for exactly this reason, and a permutation null
runs underneath because with n=13 "above 0.5" is not the same as "above
chance".

WHAT SEPARATES THEM IS BROADBAND, NOT A FAST RIPPLE
===================================================
The single best feature is MUA-band power, 600-2000 Hz (AUC 0.91), and
spectral entropy is HIGHER in IEDs (0.91 vs 0.75). The HFO literature
associates pathological fast ripples with LOW entropy -- narrowband, peaked.
High entropy is the signature of broadband energy: a sharp transient, or
multiunit firing, or a band-pass filter ringing on a step.

So the honest reading of this session is that IEDs differ from dentate spikes
by how much broadband high-frequency energy they carry -- most consistent with
greater multiunit recruitment -- and NOT by containing a narrowband fast-ripple
oscillation that dentate spikes lack. The three guards that make that
statement checkable (entropy, sustained cycles, and a FOOOF peak above the
aperiodic fit) are all in the feature table and all plotted.

CAVEAT ON THE LAMINAR BLOCK
===========================
The CSD sink lands in DG GCL2 for both classes and the laminar features do not
discriminate (AUC 0.55, not distinguishable from the permutation null). Two
readings, and this session cannot separate them: either both event types are
generated by the same dentate circuitry and differ only in high-frequency
recruitment, or the CSD is being run over a channel order that is not a depth
order. The session registry records no probe type; the anatomy CSV runs CA1 ->
SLM -> OML1 -> MML1 -> GCL1 -> HIL -> GCL2 -> MML2 -> OML2 continuously across
the 32/33 boundary, which is a single descending shank and is why a CSD down
CSC order is run at all -- but `probes.py` documents an H10-D on which that
order would be wrong. Bragin's dentate-spike sink belongs in the MOLECULAR
layer; getting GCL2 is close to it but not it. Worth settling against the
implant record before the laminar numbers are used for anything.

RUN
===
  python ied_ampwidth_gui_v7.py
  python ied_ampwidth_gui_v7.py --set spectral
"""
from __future__ import annotations

import argparse
import os
import sys

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection
from matplotlib.colors import to_rgba
from matplotlib.widgets import Button, CheckButtons, RadioButtons, TextBox

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _HERE)

from ied_ds import ANAT, BAD_CHANNELS, DS_BANK, NCS_FOLDER, Probe64  # noqa: E402
from ied_ds_lit import (BANDS, EVENT_WIN_MS, FEATURES, all_features,  # noqa: E402
                        auc1, bp, build, csd, envelope, evaluate, run_pca)

INK = "#1b2220"
BADC = "#c0392b"
IEDC = "#b8620a"
DSC = "#1f6feb"
WINC = "#0b7a63"
HFC = "#0aa5c8"
CLASS_C = {"IED": IEDC, "DS": DSC}

SETS = {
    "spectral": ["fr_db", "ripple_db", "mua_db", "fr_ripple_ratio",
                 "spec_entropy", "hfo_cycles", "fooof_exp", "fooof_peak_pw"],
    "morphology": ["amp_uV", "hw_ms", "max_slope", "sharpness", "asym",
                   "slow_wave_uV"],
    "laminar": ["csd_sink_row", "csd_dipole_rows", "spread_contacts"],
    "amp + HW (v6)": ["amp_uV", "hw_ms"],
    "ALL": list(FEATURES),
}
BAND_ORDER = ["lfp", "ripple", "fast_ripple", "mua"]
BAND_C = {"lfp": "#1b2220", "ripple": "#7b3fa0", "fast_ripple": "#0aa5c8",
          "mua": "#b8620a"}

OUT = os.path.join(_HERE, "ied_ds_v7_features.csv")


class Bench:
    def __init__(self, args):
        self.args = args
        self.setname = args.set
        self.view_ms = args.view_ms
        self.sel = 0
        self._eval = {}
        self._note = ""

        self.p = Probe64(args.folder, BAD_CHANNELS, args.anat)
        self._build()
        _, self.st = build(self.p, category=args.category,
                           progress=self._progress, refresh=args.refresh)
        self.shift, _ = self.st.centre_all(
            np.zeros(len(self.st), dtype=int), 50.0, "mean|amp| peak", True)
        self._progress(0, 1, "extracting literature features ...")
        self.tab = all_features(self.st, self.p, self.shift,
                                progress=self._progress)
        self._progress(1, 1, "")
        self.fit()
        self.draw()

    # ------------------------------------------------------------- analysis
    @property
    def feats(self):
        return [f for f in SETS[self.setname] if f in self.tab.columns]

    def fit(self):
        self.pca = run_pca(self.tab, self.feats)

    def evaluation(self):
        """Out-of-fold AUC for the current set, cached -- it is not cheap."""
        key = (self.setname, tuple(self.feats))
        if key not in self._eval:
            self._progress(0, 1, "cross-validating %s ..." % self.setname)
            self._eval[key] = evaluate(self.tab, self.feats,
                                       n_repeats=10, n_perm=100)
            self._progress(1, 1, "")
        return self._eval[key]

    @property
    def row(self):
        return self.tab.iloc[self.sel % len(self.tab)]

    # ---------------------------------------------------------------- build
    def _build(self):
        self.fig = plt.figure(figsize=(19.0, 10.4), facecolor="white")
        self.fig.canvas.manager.set_window_title(
            "IED vs DS -- literature features, CSD, cross-validated PCA (v7)")
        self.ax_stack = self.fig.add_axes([0.042, 0.300, 0.150, 0.630])
        self.ax_band = self.fig.add_axes([0.222, 0.300, 0.190, 0.630])
        self.ax_csd = self.fig.add_axes([0.448, 0.300, 0.160, 0.630])
        self.ax_pca = self.fig.add_axes([0.652, 0.560, 0.150, 0.370])
        self.ax_auc = self.fig.add_axes([0.652, 0.075, 0.150, 0.330])
        self.ax_cv = self.fig.add_axes([0.845, 0.560, 0.145, 0.370])

        self.fig.canvas.mpl_connect("button_press_event", self.on_click)
        self.fig.canvas.mpl_connect("key_press_event", self.on_key)
        b = lambda l, t, w, h: self.fig.add_axes([l, t, w, h])

        self.r_set = RadioButtons(b(0.042, 0.095, 0.105, 0.135),
                                  list(SETS), active=list(SETS).index(self.setname))
        self.r_set.on_clicked(self.on_set)
        self.fig.text(0.042, 0.236, "feature set", fontsize=8, color=INK)

        self.b_prev = Button(b(0.170, 0.196, 0.034, 0.032), "< prev")
        self.b_next = Button(b(0.208, 0.196, 0.034, 0.032), "next >")
        self.b_prev.on_clicked(lambda _: self.step(-1))
        self.b_next.on_clicked(lambda _: self.step(+1))
        self.b_cls = Button(b(0.170, 0.158, 0.072, 0.032), "next IED")
        self.b_cls.on_clicked(lambda _: self.next_class())
        self.b_cv = Button(b(0.170, 0.120, 0.072, 0.032), "cross-validate")
        self.b_cv.on_clicked(lambda _: self.do_eval())
        self.b_exp = Button(b(0.170, 0.082, 0.072, 0.032), "export")
        self.b_exp.on_clicked(lambda _: self.export())

        self.txt = self.fig.text(0.845, 0.500, "", fontsize=8.2, color=INK,
                                 va="top", family="monospace")
        self.stat_txt = self.fig.text(0.042, 0.040, "", fontsize=8.5,
                                      color=INK, va="top", family="monospace")

    def _progress(self, i, n, msg):
        self.stat_txt.set_text("[%d/%d] %s" % (i, n, msg) if msg else "")
        try:
            self.fig.canvas.draw_idle()
            self.fig.canvas.flush_events()
        except Exception:
            pass

    # ------------------------------------------------------------ callbacks
    def on_click(self, ev):
        if ev.inaxes is not self.ax_pca or ev.xdata is None:
            return
        tb = getattr(self.fig.canvas.manager, "toolbar", None)
        if tb is not None and getattr(tb, "mode", ""):
            return
        S = self.pca["scores"]
        ax = self.ax_pca
        (x0, x1), (y0, y1) = ax.get_xlim(), ax.get_ylim()
        sx, sy = (x1 - x0) or 1.0, (y1 - y0) or 1.0
        Y = S[:, 1] if S.shape[1] > 1 else np.zeros(len(S))
        d = ((S[:, 0] - ev.xdata) / sx) ** 2 + ((Y - ev.ydata) / sy) ** 2
        self.sel = int(np.nanargmin(d))
        self.draw()

    def on_key(self, ev):
        if ev.key == "right":
            self.step(+1)
        elif ev.key == "left":
            self.step(-1)
        elif ev.key == "tab":
            self.next_class()
        elif ev.key == "v":
            self.do_eval()
        elif ev.key == "e":
            self.export()

    def step(self, d):
        self.sel = (self.sel + d) % len(self.tab)
        self.draw()

    def next_class(self):
        want = "DS" if str(self.row["kind"]) == "IED" else "IED"
        k = self.tab["kind"].to_numpy()
        for j in range(1, len(k) + 1):
            m = (self.sel + j) % len(k)
            if k[m] == want:
                self.sel = m
                break
        self.b_cls.label.set_text("next %s" % ("IED" if want == "DS" else "DS"))
        self.draw()

    def on_set(self, label):
        self.setname = label
        self.fit()
        self.draw()

    def do_eval(self):
        self.evaluation()
        self.draw()

    def export(self):
        out = self.tab.copy()
        S = self.pca["scores"]
        for k in range(min(3, S.shape[1])):
            out["PC%d" % (k + 1)] = S[:, k]
        out["feature_set"] = self.setname
        out.to_csv(OUT, index=False)
        self.draw(note="exported -> %s" % os.path.basename(OUT))

    # -------------------------------------------------------------- drawing
    def draw(self, note=""):
        self._stack()
        self._bands()
        self._csd()
        self._pca()
        self._aucbar()
        self._cvpanel()
        self._readout(note)
        self.fig.canvas.draw_idle()

    def _win(self, i):
        c = self.st.stamp_i + int(self.shift[i])
        h = int(round(self.view_ms * 1e-3 * self.st.fs))
        return max(0, c - h), min(self.st.data.shape[1], c + h + 1), c

    def _stack(self):
        ax = self.ax_stack
        ax.clear()
        r = self.row
        i = int(r["idx"])
        lo, hi, c = self._win(i)
        y = bp(self.st.trace(i)[lo:hi], self.st.fs, BANDS["lfp"])
        t = (np.arange(lo, hi) - c) / self.st.fs * 1e3
        per = np.nanpercentile(np.abs(y - np.nanmedian(y, axis=0)), 99.0, axis=0)
        step = max(2.0 * float(np.nanmedian(per)), 1e-6)
        wl, wh = int(r["contact_row"]), int(r["hf_contact_row"])
        cols, lws = [], []
        for k in range(y.shape[1]):
            if k == wl:
                cols.append(to_rgba(WINC, 1.0)); lws.append(1.7)
            elif k == wh:
                cols.append(to_rgba(HFC, 1.0)); lws.append(1.5)
            elif not self.p.included[k]:
                cols.append(to_rgba(BADC, 0.4)); lws.append(0.7)
            else:
                cols.append(to_rgba(CLASS_C[str(r["kind"])], 1.0)); lws.append(0.7)
        ax.add_collection(LineCollection(
            [np.column_stack((t, y[:, k] - k * step)) for k in range(y.shape[1])],
            colors=cols, linewidths=lws, zorder=3))
        ax.axvline(0.0, color="#333333", lw=1.2, zorder=6)
        ax.axvspan(-EVENT_WIN_MS, EVENT_WIN_MS, color="#999999", alpha=0.12,
                   zorder=0)
        ticks = list(range(0, y.shape[1], 4))
        ax.set_yticks([-k * step for k in ticks])
        ax.set_yticklabels([self.p.label(k) for k in ticks], fontsize=6)
        ax.set_ylim(-(y.shape[1] - 0.2) * step, step)
        ax.set_xlim(-self.view_ms, self.view_ms)
        ax.set_xlabel("ms from centre", fontsize=8.5)
        ax.set_title("%s %d   1-100 Hz\ngreen = LFP peak, cyan = HF peak"
                     % (r["kind"], r["id"]), fontsize=9)

    def _bands(self):
        """The same contact through each literature band. The 'right filters'."""
        ax = self.ax_band
        ax.clear()
        r = self.row
        i, w = int(r["idx"]), int(r["hf_contact_row"])
        lo, hi, c = self._win(i)
        x = self.st.trace(i)[:, w]
        t = (np.arange(lo, hi) - c) / self.st.fs * 1e3
        off = 0.0
        for name in BAND_ORDER:
            v = bp(x, self.st.fs, BANDS[name])[lo:hi]
            sc = np.percentile(np.abs(v), 99.5) or 1.0
            ax.plot(t, v / sc + off, lw=0.9, color=BAND_C[name])
            if name != "lfp":
                e = envelope(x, self.st.fs, BANDS[name])[lo:hi]
                ax.plot(t, e / sc + off, lw=1.4, color=BAND_C[name], alpha=0.55)
            ax.text(-self.view_ms * 0.97, off + 1.25,
                    "%s  %.0f-%.0f Hz   (x%.0f µV)"
                    % (name, BANDS[name][0], BANDS[name][1], sc),
                    fontsize=7, color=BAND_C[name])
            off -= 3.2
        ax.axvline(0.0, color="#333333", lw=1.2)
        ax.axvspan(-EVENT_WIN_MS, EVENT_WIN_MS, color="#999999", alpha=0.12, lw=0)
        ax.set_xlim(-self.view_ms, self.view_ms)
        ax.set_yticks([])
        ax.set_xlabel("ms from centre", fontsize=8.5)
        ax.set_title("%s   zero-phase bands (thick = envelope)\n"
                     "FR %+.1f dB   MUA %+.1f dB   entropy %.2f   cycles %.1f"
                     % (self.p.label(w), r["fr_db"], r["mua_db"],
                        r["spec_entropy"], r["hfo_cycles"]), fontsize=9)

    def _csd(self):
        ax = self.ax_csd
        ax.clear()
        r = self.row
        i = int(r["idx"])
        lo, hi, c = self._win(i)
        lfp = bp(self.st.trace(i)[lo:hi], self.st.fs, BANDS["lfp"])
        cs = csd(lfp, self.p.included)
        t = (np.arange(lo, hi) - c) / self.st.fs * 1e3
        v = np.nanpercentile(np.abs(cs), 99.0) or 1.0
        im = ax.pcolormesh(t, np.arange(cs.shape[1]), cs.T, cmap="bwr",
                           vmin=-v, vmax=v, shading="nearest")
        if np.isfinite(r["csd_sink_row"]):
            ax.axhline(r["csd_sink_row"], color="#111111", lw=1.3)
            ax.text(self.view_ms * 0.96, r["csd_sink_row"], " sink", ha="right",
                    va="bottom", fontsize=7.5, color="#111111")
        for cbad in np.where(~self.p.included)[0]:
            ax.axhline(cbad, color="#444444", lw=0.7, ls=":")
        ax.axvline(0.0, color="#333333", lw=1.0)
        ax.invert_yaxis()
        ax.set_yticks(range(0, cs.shape[1], 4))
        ax.set_yticklabels([self.p.label(k) for k in range(0, cs.shape[1], 4)],
                           fontsize=6)
        ax.set_xlim(-self.view_ms, self.view_ms)
        ax.set_xlabel("ms from centre", fontsize=8.5)
        ax.set_title("CSD  (blue = sink)\nsink %s   dipole %.0f contacts"
                     % (r.get("csd_sink_region", "?"), r["csd_dipole_rows"]),
                     fontsize=9)
        if not hasattr(self, "_cb"):
            self._cb = self.fig.colorbar(im, ax=ax, pad=0.01, fraction=0.045)
            self._cb.ax.tick_params(labelsize=6)
        else:
            self._cb.update_normal(im)

    def _pca(self):
        ax = self.ax_pca
        ax.clear()
        S = self.pca["scores"]
        y = self.pca["y"]
        ev = self.pca["explained"]
        Y = S[:, 1] if S.shape[1] > 1 else np.zeros(len(S))
        for kind, m in (("DS", ~y), ("IED", y)):
            ax.plot(S[m, 0], Y[m], "o", ms=3.4 if kind == "IED" else 2.4,
                    color=CLASS_C[kind], alpha=0.8 if kind == "IED" else 0.35,
                    mec="none", zorder=4 if kind == "IED" else 3,
                    label="%s n=%d" % (kind, int(m.sum())))
        ax.plot(S[self.sel, 0], Y[self.sel], "o", ms=11, mfc="none",
                mec=WINC, mew=2.0, zorder=6)
        ax.set_xlabel("PC1 (%.0f%%)" % (100 * ev[0]), fontsize=8.5)
        ax.set_ylabel("PC2 (%.0f%%)" % (100 * ev[1]) if len(ev) > 1 else "",
                      fontsize=8.5)
        ax.set_title("PCA of '%s'   (click a dot)" % self.setname, fontsize=9)
        ax.legend(fontsize=7, framealpha=0.9)
        ax.tick_params(labelsize=7)

    def _aucbar(self):
        ax = self.ax_auc
        ax.clear()
        y = self.pca["y"]
        vals = [(f, auc1(self.tab[f].to_numpy(), y)) for f in self.feats]
        vals = [(f, v) for f, v in vals if np.isfinite(v)]
        vals.sort(key=lambda kv: abs(kv[1] - 0.5))
        names = [f for f, _ in vals]
        a = np.array([v for _, v in vals])
        yy = np.arange(len(a))
        ax.barh(yy, a - 0.5, left=0.5, height=0.7,
                color=[IEDC if v >= 0.5 else DSC for v in a], alpha=0.85)
        ax.axvline(0.5, color="#333333", lw=1.0)
        ax.set_yticks(yy)
        ax.set_yticklabels(names, fontsize=7.5)
        ax.set_xlim(0.25, 0.98)
        ax.set_xlabel("AUC per feature   (0.5 = chance)", fontsize=8.5)
        ax.set_title("which features carry the signal", fontsize=9)
        ax.tick_params(labelsize=7)

    def _cvpanel(self):
        ax = self.ax_cv
        ax.clear()
        done = [(name, self._eval[k]) for name in SETS
                for k in [(name, tuple(f for f in SETS[name]
                                       if f in self.tab.columns))]
                if k in self._eval]
        if not done:
            ax.text(0.5, 0.5, "press 'cross-validate'\n(or v) for this set",
                    ha="center", va="center", fontsize=9, color="#666666")
            ax.set_xticks([]); ax.set_yticks([])
            ax.set_title("out-of-fold performance", fontsize=9)
            return
        yy = np.arange(len(done))
        cv = np.array([d["cv_auc"] for _, d in done])
        sd = np.array([d["cv_sd"] for _, d in done])
        ins = np.array([d["in_sample_auc"] for _, d in done])
        nul = np.array([d["null_p95"] for _, d in done])
        ax.barh(yy + 0.18, ins, height=0.34, color="#c8c8c8",
                label="in-sample (optimistic)")
        ax.barh(yy - 0.18, cv, height=0.34, xerr=sd, color=WINC,
                error_kw=dict(lw=1.0, ecolor="#333333"), label="out-of-fold")
        ax.plot(nul, yy - 0.18, "|", ms=12, color=BADC, mew=2.0,
                label="null 95th pct")
        ax.axvline(0.5, color="#333333", lw=0.9, ls=":")
        ax.set_yticks(yy)
        ax.set_yticklabels([n for n, _ in done], fontsize=7.5)
        ax.set_xlim(0.4, 1.0)
        ax.set_xlabel("AUC", fontsize=8.5)
        ax.set_title("out-of-fold vs in-sample", fontsize=9)
        ax.legend(fontsize=6.5, framealpha=0.9, loc="lower right")
        ax.tick_params(labelsize=7)

    def _readout(self, note=""):
        y = self.pca["y"]
        L = ["set      %s  (%d features)" % (self.setname, len(self.feats)),
             "events   IED %d   DS %d" % (int(y.sum()), int((~y).sum())),
             "bands    LFP 1-100  ripple 80-250" ,
             "         FR 250-600  MUA 600-2000 Hz",
             ""]
        key = (self.setname, tuple(self.feats))
        if key in self._eval:
            r = self._eval[key]
            L.append("out-of-fold AUC  %.3f +- %.3f" % (r["cv_auc"], r["cv_sd"]))
            L.append("in-sample   AUC  %.3f" % r["in_sample_auc"])
            L.append("null 95th pct    %.3f    p=%.3f"
                     % (r["null_p95"], r["p_perm"]))
            gap = r["in_sample_auc"] - r["cv_auc"]
            if gap > 0.08:
                L.append("")
                L.append("in-sample beats out-of-fold by %.2f:" % gap)
                L.append("this set is overfitting 13 positives.")
        else:
            L.append("press 'cross-validate' (v)")
        L.append("")
        L.append("PCA explained %s"
                 % " ".join("%.2f" % v for v in self.pca["explained"][:4]))
        best = max(((abs(auc1(self.tab[f].to_numpy(), y) - 0.5), f)
                    for f in self.feats), default=(0, "-"))
        L.append("best single: %s" % best[1])
        if note or self._note:
            L.append("")
            L.append(note or self._note)
        self.txt.set_text("\n".join(L))

        r = self.row
        self.stat_txt.set_text(
            "%s %d  t=%.2f s  LFP peak %s  HF peak %s  amp %.0f uV  "
            "HW %.1f ms  FR %+.1f dB%s"
            % (r["kind"], r["id"], r["t_s"], self.p.label(int(r["contact_row"])),
               self.p.label(int(r["hf_contact_row"])), r["amp_uV"], r["hw_ms"],
               r["fr_db"], "   RAILED" if bool(r["railed"]) else ""))


def main():
    ap = argparse.ArgumentParser(
        description="IED vs DS: literature features, CSD, cross-validated")
    ap.add_argument("--folder", default=NCS_FOLDER)
    ap.add_argument("--ds-bank", default=DS_BANK)
    ap.add_argument("--anat", default=ANAT)
    ap.add_argument("--category", default="Solid")
    ap.add_argument("--set", default="spectral", choices=list(SETS))
    ap.add_argument("--view-ms", type=float, default=100.0)
    ap.add_argument("--refresh", action="store_true")
    args = ap.parse_args()
    Bench(args)
    plt.show()


if __name__ == "__main__":
    main()
