FILTER OFF.
USE ALL.

* ============================================================.
* GEE per region -- reference = Base, IP (via ORDER=DESCENDING).
* Also prints pairwise: Base-vs-CNO and IP-vs-PP per region.
* Stacked file: Mouse Condition Phase Region Voltage.
* ============================================================.

TITLE "REGION 1 of 8:  CA1 SLM".
TEMPORARY.
SELECT IF Region = "CA1 SLM".
GENLIN Voltage BY Condition Phase (ORDER=DESCENDING)
  /MODEL Condition*Phase INTERCEPT=YES DISTRIBUTION=NORMAL LINK=IDENTITY
  /CRITERIA SCALE=MLE SINGULAR=1E-012 ANALYSISTYPE=3(WALD) CILEVEL=95 LIKELIHOOD=FULL
  /EMMEANS TABLES=Condition*Phase SCALE=ORIGINAL COMPARE=Condition CONTRAST=PAIRWISE PADJUST=LSD
  /EMMEANS TABLES=Condition*Phase SCALE=ORIGINAL COMPARE=Phase CONTRAST=PAIRWISE PADJUST=LSD
  /REPEATED SUBJECT=Mouse SORT=YES CORRTYPE=INDEPENDENT ADJUSTCORR=YES COVB=ROBUST
  /MISSING CLASSMISSING=EXCLUDE
  /PRINT CPS MODELINFO FIT SUMMARY SOLUTION.

TITLE "REGION 2 of 8:  DG OML1".
TEMPORARY.
SELECT IF Region = "DG OML1".
GENLIN Voltage BY Condition Phase (ORDER=DESCENDING)
  /MODEL Condition*Phase INTERCEPT=YES DISTRIBUTION=NORMAL LINK=IDENTITY
  /CRITERIA SCALE=MLE SINGULAR=1E-012 ANALYSISTYPE=3(WALD) CILEVEL=95 LIKELIHOOD=FULL
  /EMMEANS TABLES=Condition*Phase SCALE=ORIGINAL COMPARE=Condition CONTRAST=PAIRWISE PADJUST=LSD
  /EMMEANS TABLES=Condition*Phase SCALE=ORIGINAL COMPARE=Phase CONTRAST=PAIRWISE PADJUST=LSD
  /REPEATED SUBJECT=Mouse SORT=YES CORRTYPE=INDEPENDENT ADJUSTCORR=YES COVB=ROBUST
  /MISSING CLASSMISSING=EXCLUDE
  /PRINT CPS MODELINFO FIT SUMMARY SOLUTION.

TITLE "REGION 3 of 8:  DG MML1".
TEMPORARY.
SELECT IF Region = "DG MML1".
GENLIN Voltage BY Condition Phase (ORDER=DESCENDING)
  /MODEL Condition*Phase INTERCEPT=YES DISTRIBUTION=NORMAL LINK=IDENTITY
  /CRITERIA SCALE=MLE SINGULAR=1E-012 ANALYSISTYPE=3(WALD) CILEVEL=95 LIKELIHOOD=FULL
  /EMMEANS TABLES=Condition*Phase SCALE=ORIGINAL COMPARE=Condition CONTRAST=PAIRWISE PADJUST=LSD
  /EMMEANS TABLES=Condition*Phase SCALE=ORIGINAL COMPARE=Phase CONTRAST=PAIRWISE PADJUST=LSD
  /REPEATED SUBJECT=Mouse SORT=YES CORRTYPE=INDEPENDENT ADJUSTCORR=YES COVB=ROBUST
  /MISSING CLASSMISSING=EXCLUDE
  /PRINT CPS MODELINFO FIT SUMMARY SOLUTION.

TITLE "REGION 4 of 8:  DG GCL1".
TEMPORARY.
SELECT IF Region = "DG GCL1".
GENLIN Voltage BY Condition Phase (ORDER=DESCENDING)
  /MODEL Condition*Phase INTERCEPT=YES DISTRIBUTION=NORMAL LINK=IDENTITY
  /CRITERIA SCALE=MLE SINGULAR=1E-012 ANALYSISTYPE=3(WALD) CILEVEL=95 LIKELIHOOD=FULL
  /EMMEANS TABLES=Condition*Phase SCALE=ORIGINAL COMPARE=Condition CONTRAST=PAIRWISE PADJUST=LSD
  /EMMEANS TABLES=Condition*Phase SCALE=ORIGINAL COMPARE=Phase CONTRAST=PAIRWISE PADJUST=LSD
  /REPEATED SUBJECT=Mouse SORT=YES CORRTYPE=INDEPENDENT ADJUSTCORR=YES COVB=ROBUST
  /MISSING CLASSMISSING=EXCLUDE
  /PRINT CPS MODELINFO FIT SUMMARY SOLUTION.

TITLE "REGION 5 of 8:  HIL".
TEMPORARY.
SELECT IF Region = "HIL".
GENLIN Voltage BY Condition Phase (ORDER=DESCENDING)
  /MODEL Condition*Phase INTERCEPT=YES DISTRIBUTION=NORMAL LINK=IDENTITY
  /CRITERIA SCALE=MLE SINGULAR=1E-012 ANALYSISTYPE=3(WALD) CILEVEL=95 LIKELIHOOD=FULL
  /EMMEANS TABLES=Condition*Phase SCALE=ORIGINAL COMPARE=Condition CONTRAST=PAIRWISE PADJUST=LSD
  /EMMEANS TABLES=Condition*Phase SCALE=ORIGINAL COMPARE=Phase CONTRAST=PAIRWISE PADJUST=LSD
  /REPEATED SUBJECT=Mouse SORT=YES CORRTYPE=INDEPENDENT ADJUSTCORR=YES COVB=ROBUST
  /MISSING CLASSMISSING=EXCLUDE
  /PRINT CPS MODELINFO FIT SUMMARY SOLUTION.

TITLE "REGION 6 of 8:  DG GCL2".
TEMPORARY.
SELECT IF Region = "DG GCL2".
GENLIN Voltage BY Condition Phase (ORDER=DESCENDING)
  /MODEL Condition*Phase INTERCEPT=YES DISTRIBUTION=NORMAL LINK=IDENTITY
  /CRITERIA SCALE=MLE SINGULAR=1E-012 ANALYSISTYPE=3(WALD) CILEVEL=95 LIKELIHOOD=FULL
  /EMMEANS TABLES=Condition*Phase SCALE=ORIGINAL COMPARE=Condition CONTRAST=PAIRWISE PADJUST=LSD
  /EMMEANS TABLES=Condition*Phase SCALE=ORIGINAL COMPARE=Phase CONTRAST=PAIRWISE PADJUST=LSD
  /REPEATED SUBJECT=Mouse SORT=YES CORRTYPE=INDEPENDENT ADJUSTCORR=YES COVB=ROBUST
  /MISSING CLASSMISSING=EXCLUDE
  /PRINT CPS MODELINFO FIT SUMMARY SOLUTION.

TITLE "REGION 7 of 8:  DG MML2".
TEMPORARY.
SELECT IF Region = "DG MML2".
GENLIN Voltage BY Condition Phase (ORDER=DESCENDING)
  /MODEL Condition*Phase INTERCEPT=YES DISTRIBUTION=NORMAL LINK=IDENTITY
  /CRITERIA SCALE=MLE SINGULAR=1E-012 ANALYSISTYPE=3(WALD) CILEVEL=95 LIKELIHOOD=FULL
  /EMMEANS TABLES=Condition*Phase SCALE=ORIGINAL COMPARE=Condition CONTRAST=PAIRWISE PADJUST=LSD
  /EMMEANS TABLES=Condition*Phase SCALE=ORIGINAL COMPARE=Phase CONTRAST=PAIRWISE PADJUST=LSD
  /REPEATED SUBJECT=Mouse SORT=YES CORRTYPE=INDEPENDENT ADJUSTCORR=YES COVB=ROBUST
  /MISSING CLASSMISSING=EXCLUDE
  /PRINT CPS MODELINFO FIT SUMMARY SOLUTION.

TITLE "REGION 8 of 8:  DG OML2  (n=3-4 mice -- UNDERPOWERED)".
TEMPORARY.
SELECT IF Region = "DG OML2".
GENLIN Voltage BY Condition Phase (ORDER=DESCENDING)
  /MODEL Condition*Phase INTERCEPT=YES DISTRIBUTION=NORMAL LINK=IDENTITY
  /CRITERIA SCALE=MLE SINGULAR=1E-012 ANALYSISTYPE=3(WALD) CILEVEL=95 LIKELIHOOD=FULL
  /EMMEANS TABLES=Condition*Phase SCALE=ORIGINAL COMPARE=Condition CONTRAST=PAIRWISE PADJUST=LSD
  /EMMEANS TABLES=Condition*Phase SCALE=ORIGINAL COMPARE=Phase CONTRAST=PAIRWISE PADJUST=LSD
  /REPEATED SUBJECT=Mouse SORT=YES CORRTYPE=INDEPENDENT ADJUSTCORR=YES COVB=ROBUST
  /MISSING CLASSMISSING=EXCLUDE
  /PRINT CPS MODELINFO FIT SUMMARY SOLUTION.

TITLE "".